### ISSUE TITLE
INSUFFICIENT VARIABLES

### ISSUE THREAD

**Issue by Brianjoroge** [dsynkov/smmry-api-wrapper#1]
thanks, but i have an issue, following your instructions i run 

import os

SMMRY_API_KEY = os.environ.get('SMMRY_API_KEY')

from smmryapi import SmmryAPI

smmry = SmmryAPI(SMMRY_API_KEY)

url = 'http://www.bbc.com/news/business-43298897'

s = smmry.summarize(url,sm_length=3)

print(s.sm_api_content) 

OUTPUT:
SmmryAPIException: 1: INSUFFICIENT VARIABLES

**Comment by jcprimo** [comment]
Did you get any errors during the process of installation?  I got my instance up and running.

**Comment by dsynkov** [comment]
Are you sure that your `SMMRY_API_KEY` environment variable is set? As in:
```
export SMMRY_API_KEY=<PASTE_SMMRY_API_KEY_HERE>
```
In your shell, or:
```
import os
os.environ['SMMRY_API_KEY'] = '<PASTE_SMMRY_API_KEY_HERE>'
```
In Python. The `os.environ.get` method will return a `NoneType` if the variable is not there, which would explain why you're seeing the  error (it's missing the key "variable").
